# Generated by Django 4.1 on 2023-04-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.IntegerField(verbose_name="词频")),
                ("position", models.IntegerField(verbose_name="位置")),
            ],
            options={
                "verbose_name": "倒排索引",
                "verbose_name_plural": "倒排索引",
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=100, verbose_name="词条")),
                ("document_count", models.IntegerField(verbose_name="出现该词条的文档数")),
            ],
            options={
                "verbose_name": "词条",
                "verbose_name_plural": "词条",
            },
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(fields=["term"], name="indexes_ter_term_e0d388_idx"),
        ),
        migrations.AddField(
            model_name="posting",
            name="doc_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.document",
                verbose_name="文档ID",
            ),
        ),
        migrations.AddField(
            model_name="posting",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="indexes.term",
                verbose_name="词条",
            ),
        ),
        migrations.AddIndex(
            model_name="posting",
            index=models.Index(fields=["term"], name="indexes_pos_term_id_fcbf93_idx"),
        ),
        migrations.AddIndex(
            model_name="posting",
            index=models.Index(
                fields=["doc_id"], name="indexes_pos_doc_id__37c248_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posting",
            index=models.Index(
                fields=["term", "doc_id"], name="indexes_pos_term_id_0a8923_idx"
            ),
        ),
    ]
