site_name: 搜索引擎
site_description: 搜索引擎文档
nav:
  - 2023年春季学期搜索引擎大作业: index.md
  - 1. 概述: 1. 概述/概述.md
  - 2. 结构设计: 
    - 2.1 项目构型: 2. 结构设计/2.1 项目构型.md
    - 2.2 仓库结构: 2. 结构设计/2.2 仓库结构.md
    - 2.3 功能划分: 2. 结构设计/2.3 功能划分.md
  - 3. 前端模块介绍: 
    - 3.1 框架图: 3. 前端模块介绍/3.1 框架图.md
    - 3.2 功能展示: 3. 前端模块介绍/3.2 功能展示.md
    - 3.3 主要函数: 3. 前端模块介绍/3.3 主要函数.md
  - 4. 后端模块介绍:
    - 4.1 数据库设计: 
      - 4.1.1 文书类型分析: 4. 后端模块介绍/4.1 common/4.1.1 文书类型分析.md
      - 4.1.2 数据库模型设计: 4. 后端模块介绍/4.1 common/4.1.2 数据库模型设计.md
    - 4.2 数据抓取子系统: 4. 后端模块介绍/4.2 数据抓取子系统.md
    - 4.3 内容索引子系统: 4. 后端模块介绍/4.3 内容索引子系统.md
    - 4.4 内容检索子系统: 
      - 4.4.1 检索子系统: 4. 后端模块介绍/4.4 内容检索子系统/4.4.1 检索子系统.md
      - 4.4.2 解析子系统: 4. 后端模块介绍/4.4 内容检索子系统/4.4.2 解析子系统.md
    - 4.5 链接分析子系统: 4. 后端模块介绍/4.5 链接分析子系统.md
  - 5. 优化过程:
    - 5.1 搜索速度优化: 5. 优化过程/5.1 搜索速度优化.md
    - 5.2 数据处理速度优化: 5. 优化过程/5.2 数据处理速度优化.md
    - 5.3 索引建立速度优化: 5. 优化过程/5.3 索引建立速度优化.md
  - 附1. 所有文书类型分析:
    - 1.1 法院文书:
      - 1.1.1 裁判文书(判决书+裁定书+调解书): old/1.不同文书分析/法院/1. 判决书 裁定书 调解书 (即 裁判文书).md
      - 1.1.2 决定书: old/1.不同文书分析/法院/2. 决定书.md
      - 1.1.3 起诉状: old/1.不同文书分析/法院/3. 起诉状.md
      - 1.1.4 通知书: old/1.不同文书分析/法院/4. 通知书.md
    - 1.2 检察院文书:
      - 1.2.1 起诉书: old/1.不同文书分析/检察院/1. 起诉书.md
      - 1.2.2 不起诉书: old/1.不同文书分析/检察院/2. 不起诉书.md
    - 1.3 司法行政文书:
      - 1.3.1 暂予监外执行案例: old/1.不同文书分析/司法行政/暂予监外执行案例.md
  - 附2. 优化sqlite3: 附/优化sqlite3.md

#   - 0.基础设计:
#     - 1.1 架构: 0.搜索引擎设计/1. 架构.md
#     - 1.2 分析文书: 0.搜索引擎设计/3. 分析文书.md
#   - 1.不同文书分析:
#     - 1.1 法院文书:
#       - 1.1.1 裁判文书(判决书+裁定书+调解书): 1.不同文书分析/法院/1. 判决书 裁定书 调解书 (即 裁判文书).md
#       - 1.1.2 决定书: 1.不同文书分析/法院/2. 决定书.md
#       - 1.1.3 起诉状: 1.不同文书分析/法院/3. 起诉状.md
#       - 1.1.4 通知书: 1.不同文书分析/法院/4. 通知书.md
#     - 1.2 检察院文书:
#       - 1.2.1 起诉书: 1.不同文书分析/检察院/1. 起诉书.md
#       - 1.2.2 不起诉书: 1.不同文书分析/检察院/2. 不起诉书.md
#     - 1.3 司法行政文书:
#       - 1.3.1 暂予监外执行案例: 1.不同文书分析/司法行政/暂予监外执行案例.md
#   - 2.数据库设计:
#     - 2.1 原则: 2.创建模型/1.原则.md
#     - 2.2 模型: 2.创建模型/3.实际使用的模型.md
# #    - 2.3 模型: 2.模型设计/3. 模型评估.md
# #    - 2.4 模型: 2.模型设计/2. 模型训练.md
# #    - 2.5 模型: 2.模型设计/3. 模型评估.md
# #    - 2.6 模型: 2.模型设计/2. 模型训练.md
#   - 3.数据抓取子系统:
#       - 3.1 数据读入: 3.数据读入/1. 数据读入.md
#       - 3.2 速度优化: 3.数据读入/4. 速度优化.md
#   - 4.内容索引子系统:
#       - 4.1 模型: 4.内容索引/1.模型.md
#       - 4.2 分词: 4.内容索引/2.分词.md
#       - 4.3 倒排索引: 4.内容索引/3.倒排索引建立.md
#       - 4.4 索引查询: 4.内容索引/4.索引查询.md
#   - 5.内容检索子系统:
#     - 5.1 查询模块:
#       - 5.1.1 联合查询: 5.内容检索/查询模块/1.分词并进行联合查询.md
#     - 5.2 解析模块:
#       - 5.2.1 解析模块: 5.内容检索/解析模块/1.TODO.md


#主题
theme:
  name: 'material'
  language: 'zh'  # 配置语言
  palette: # 颜色
    primary: 'purple'
    accent: 'indigo'
  feature:
    tabs: true  # 横向导航

markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  # - pymdownx.betterem:  # 对加粗和斜体更好的检测
  #     smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

# PDF导出插件
plugins:
  - search
#  - pdf-export #这个插件还有点问题，没有更新

#扩展样式
extra_css:
  - resources/css/extra.css