# Generated by Django 4.1 on 2023-04-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="代理人名称")),
                ("h_type", models.CharField(max_length=10, verbose_name="代理人类型")),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="代理人辩护人职业类型"
                    ),
                ),
                (
                    "a_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="辩护人或诉讼代理人类型"
                    ),
                ),
            ],
            options={
                "verbose_name": "代理人",
                "verbose_name_plural": "代理人",
            },
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="法院名称")),
                ("code", models.CharField(max_length=10, verbose_name="法院层级码")),
                ("level", models.CharField(max_length=10, verbose_name="法院级别")),
                ("province", models.CharField(max_length=30, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
            ],
            options={
                "verbose_name": "法院",
                "verbose_name_plural": "法院",
            },
        ),
        migrations.CreateModel(
            name="DocAgentParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "文书代理人当事人关系",
                "verbose_name_plural": "文书代理人当事人关系",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100, verbose_name="地址")),
                (
                    "agency",
                    models.CharField(
                        choices=[("1", "法院"), ("2", "检察院"), ("3", "司法行政")],
                        max_length=20,
                        verbose_name="文书制作单位",
                    ),
                ),
                (
                    "doc_name",
                    models.CharField(blank=True, max_length=30, verbose_name="文书名称"),
                ),
                (
                    "doc_type",
                    models.CharField(blank=True, max_length=30, verbose_name="文书种类"),
                ),
                ("full_text", models.TextField(verbose_name="全文")),
            ],
            options={
                "verbose_name": "文书",
                "verbose_name_plural": "文书",
            },
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="法官名称")),
                ("full_name", models.CharField(max_length=100, verbose_name="法官全称")),
            ],
            options={
                "verbose_name": "法官",
                "verbose_name_plural": "法官",
            },
        ),
        migrations.CreateModel(
            name="LawReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("law_name", models.CharField(max_length=100, verbose_name="法律名称")),
                (
                    "law_clause",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="条"
                    ),
                ),
                (
                    "law_clause_item",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="款"
                    ),
                ),
                (
                    "law_item",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="项"
                    ),
                ),
            ],
            options={
                "verbose_name": "法条引用",
                "verbose_name_plural": "法条引用",
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="当事人名称")),
                ("name_is_fuzzy", models.BooleanField(verbose_name="当事人名称是否模糊")),
                ("h_type", models.CharField(max_length=10, verbose_name="当事人类型")),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=10, verbose_name="国籍"),
                ),
                (
                    "nation",
                    models.CharField(blank=True, max_length=10, verbose_name="民族"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=10, verbose_name="性别"),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
            ],
            options={
                "verbose_name": "当事人",
                "verbose_name_plural": "当事人",
            },
        ),
        migrations.CreateModel(
            name="Procuratorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="检察院名称")),
                (
                    "district_code",
                    models.CharField(max_length=10, verbose_name="行政区划代码"),
                ),
                ("province", models.CharField(max_length=30, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                (
                    "county",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="区县"
                    ),
                ),
                ("level", models.IntegerField(verbose_name="检察院级别")),
            ],
            options={
                "verbose_name": "检察院",
                "verbose_name_plural": "检察院",
            },
        ),
        migrations.CreateModel(
            name="Judgment",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.document",
                    ),
                ),
                ("case_number", models.CharField(max_length=100, verbose_name="案号")),
                ("case_type", models.CharField(max_length=30, verbose_name="案件类别")),
                (
                    "judgment_date",
                    models.DateField(blank=True, null=True, verbose_name="裁判日期"),
                ),
            ],
            options={
                "verbose_name": "判决书",
                "verbose_name_plural": "判决书",
            },
            bases=("common.document",),
        ),
        migrations.CreateModel(
            name="Prosecution",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.document",
                    ),
                ),
                ("case_number", models.CharField(max_length=100, verbose_name="案号")),
                ("case_type", models.CharField(max_length=30, verbose_name="案件类别")),
                ("court", models.CharField(max_length=100, verbose_name="诉至法院")),
                (
                    "p_date",
                    models.DateField(blank=True, null=True, verbose_name="(不)起诉日期"),
                ),
            ],
            options={
                "verbose_name": "检察院文书",
                "verbose_name_plural": "检察院文书",
            },
            bases=("common.document",),
        ),
        migrations.AddIndex(
            model_name="procuratorate",
            index=models.Index(fields=["name"], name="common_proc_name_de1aac_idx"),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(fields=["name"], name="common_part_name_3f112b_idx"),
        ),
        migrations.AddIndex(
            model_name="lawreference",
            index=models.Index(
                fields=["law_name"], name="common_lawr_law_nam_68f506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lawreference",
            index=models.Index(
                fields=["law_name", "law_clause"], name="common_lawr_law_nam_49571a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lawreference",
            index=models.Index(
                fields=["law_name", "law_clause", "law_clause_item"],
                name="common_lawr_law_nam_5305ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lawreference",
            index=models.Index(
                fields=["law_name", "law_clause", "law_clause_item", "law_item"],
                name="common_lawr_law_nam_e7516c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="judge",
            index=models.Index(fields=["name"], name="common_judg_name_0f5171_idx"),
        ),
        migrations.AddIndex(
            model_name="judge",
            index=models.Index(
                fields=["full_name"], name="common_judg_full_na_8b5878_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["address"], name="common_docu_address_970137_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["agency"], name="common_docu_agency_db8431_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["doc_name"], name="common_docu_doc_nam_4c25af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["doc_type"], name="common_docu_doc_typ_bdc98e_idx"
            ),
        ),
        migrations.AddField(
            model_name="docagentparty",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.agent",
                verbose_name="代理人",
            ),
        ),
        migrations.AddField(
            model_name="docagentparty",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.party",
                verbose_name="当事人",
            ),
        ),
        migrations.AddIndex(
            model_name="court",
            index=models.Index(fields=["name"], name="common_cour_name_b907f6_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["name"], name="common_agen_name_9ef2c8_idx"),
        ),
        migrations.AddField(
            model_name="prosecution",
            name="defendant",
            field=models.ManyToManyField(
                db_index=True,
                related_name="prosecution_defendant",
                to="common.party",
                verbose_name="被告",
            ),
        ),
        migrations.AddField(
            model_name="prosecution",
            name="procuratorate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.procuratorate",
                verbose_name="检察院",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="agent",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="plaintiff_agent",
                through="common.DocAgentParty",
                to="common.agent",
                verbose_name="代理人",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="court",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.court",
                verbose_name="法院",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="defendant",
            field=models.ManyToManyField(
                db_index=True,
                related_name="defendant",
                to="common.party",
                verbose_name="被告",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="judge",
            field=models.ManyToManyField(
                db_index=True, to="common.judge", verbose_name="法官"
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="law_reference",
            field=models.ManyToManyField(
                db_index=True, to="common.lawreference", verbose_name="法条引用"
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="plaintiff",
            field=models.ManyToManyField(
                db_index=True,
                related_name="plaintiff",
                to="common.party",
                verbose_name="原告",
            ),
        ),
        migrations.AddField(
            model_name="docagentparty",
            name="doc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.judgment",
                verbose_name="文书",
            ),
        ),
        migrations.AddIndex(
            model_name="prosecution",
            index=models.Index(
                fields=["case_number"], name="common_pros_case_nu_1a5d1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prosecution",
            index=models.Index(
                fields=["case_type"], name="common_pros_case_ty_f10eea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prosecution",
            index=models.Index(fields=["p_date"], name="common_pros_p_date_910675_idx"),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["case_number"], name="common_judg_case_nu_8cc2dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["case_type"], name="common_judg_case_ty_f668c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["judgment_date"], name="common_judg_judgmen_061149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="docagentparty",
            index=models.Index(
                fields=["doc", "agent"], name="common_doca_doc_id_dc11eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="docagentparty",
            index=models.Index(
                fields=["agent", "party"], name="common_doca_agent_i_aead62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="docagentparty",
            index=models.Index(
                fields=["party", "doc"], name="common_doca_party_i_6c7af5_idx"
            ),
        ),
    ]
