# Generated by Django 4.1 on 2023-04-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="parties",
            field=models.ManyToManyField(
                db_index=True, to="common.party", verbose_name="被代理人"
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="agent",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="plaintiff_agent",
                to="common.agent",
                verbose_name="代理人",
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="defendant",
            field=models.ManyToManyField(
                db_index=True,
                related_name="defendant",
                to="common.party",
                verbose_name="被告",
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="judge",
            field=models.ManyToManyField(
                db_index=True, to="common.judge", verbose_name="法官"
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="law_reference",
            field=models.ManyToManyField(
                db_index=True, to="common.lawreference", verbose_name="法条引用"
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="plaintiff",
            field=models.ManyToManyField(
                db_index=True,
                related_name="plaintiff",
                to="common.party",
                verbose_name="原告",
            ),
        ),
        migrations.AlterField(
            model_name="prosecution",
            name="defendant",
            field=models.ManyToManyField(
                db_index=True,
                related_name="prosecution_defendant",
                to="common.party",
                verbose_name="被告",
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["name"], name="common_agen_name_9ef2c8_idx"),
        ),
        migrations.AddIndex(
            model_name="court",
            index=models.Index(fields=["name"], name="common_cour_name_b907f6_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["address"], name="common_docu_address_970137_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["agency"], name="common_docu_agency_db8431_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["doc_name"], name="common_docu_doc_nam_4c25af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["doc_type"], name="common_docu_doc_typ_bdc98e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judge",
            index=models.Index(fields=["name"], name="common_judg_name_0f5171_idx"),
        ),
        migrations.AddIndex(
            model_name="judge",
            index=models.Index(
                fields=["full_name"], name="common_judg_full_na_8b5878_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["case_number"], name="common_judg_case_nu_8cc2dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["case_type"], name="common_judg_case_ty_f668c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["judgment_date"], name="common_judg_judgmen_061149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lawreference",
            index=models.Index(
                fields=["law_name"], name="common_lawr_law_nam_68f506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lawreference",
            index=models.Index(
                fields=["law_name", "law_clause"], name="common_lawr_law_nam_49571a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lawreference",
            index=models.Index(
                fields=["law_name", "law_clause", "law_clause_item"],
                name="common_lawr_law_nam_5305ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lawreference",
            index=models.Index(
                fields=["law_name", "law_clause", "law_clause_item", "law_item"],
                name="common_lawr_law_nam_e7516c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(fields=["name"], name="common_part_name_3f112b_idx"),
        ),
        migrations.AddIndex(
            model_name="procuratorate",
            index=models.Index(fields=["name"], name="common_proc_name_de1aac_idx"),
        ),
        migrations.AddIndex(
            model_name="prosecution",
            index=models.Index(
                fields=["case_number"], name="common_pros_case_nu_1a5d1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prosecution",
            index=models.Index(
                fields=["case_type"], name="common_pros_case_ty_f10eea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prosecution",
            index=models.Index(fields=["p_date"], name="common_pros_p_date_910675_idx"),
        ),
    ]
