# Generated by Django 4.1 on 2023-04-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="party",
            name="status",
        ),
    ]
