# Generated by Django 4.1 on 2023-04-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_remove_party_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="parties",
            field=models.ManyToManyField(to="common.party", verbose_name="被代理人"),
        ),
    ]
