# Generated by Django 4.1 on 2023-04-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_agent_parties"),
    ]

    operations = [
        migrations.RenameField(
            model_name="judgment",
            old_name="plaintiff_agent",
            new_name="agent",
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="defendant_agent",
        ),
    ]
